# Generated by Django 2.1.4 on 2019-04-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
