# Generated by Django 2.1.4 on 2019-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shakes', '0003_delete_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='prof',
            field=models.ManyToManyField(blank=True, null=True, to='cart.Cart'),
        ),
    ]
