# Generated by Django 2.1.4 on 2019-04-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190410_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(null=True, upload_to='products/images/'),
        ),
    ]
